import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    ".tmp/**",
    // Generated by vitest --coverage
    "coverage/**",
    // k6 scripts use k6 globals (http, check, __ENV) que no están en
    // eslint config. Tienen /* eslint-disable */ propio.
    "loadtest/**",
    // Stryker mutation testing temp dir + reports
    ".stryker-tmp/**",
    "reports/**",
  ]),
]);

export default eslintConfig;
